add telegram-api connection, add empty command with console output
lex-cmd/LinksStorageBot pull request #3
Opened 2022-05-10 07:56 UTC by lex-cmd

Поставил временные заглушки и пока без реализации с репозиторием.

2022-05-12 12:07 UTC, appricot-project requested changes

2022-05-12 12:07 UTC, appricot-project commented on TelegramPAI/Application.cs
> +				paiBot.Start(); // получение сообщения если оно есть и запуск бота
Почему это не сделать внутри commandHandler.Execute?

2022-05-12 12:07 UTC, appricot-project commented on TelegramPAI/CommandHandler.cs
> +			if(_commandRepository.HasActiveCommand()) // проверяется есть ли сейчас активная команда и выполняет её
А как ты разделяешь в этом случае активные команды разных пользователей?

2022-05-12 12:07 UTC, appricot-project commented on TelegramPAI/CommandHandler.cs
> +				string commandResult = command.Execute(newMessage);
Я бы посоветовал завести для commandResult какой-нибудь класс DTO, так как результат выполнения команды  может быть сложнее, чем просто строка. И кроме этого, есть возможность управлять форматированием ответа внутри ResponseToChat в этом случае.

2022-05-13 06:40 UTC, lex-cmd commented on TelegramPAI/CommandHandler.cs
> +			if(_commandRepository.HasActiveCommand()) // проверяется есть ли сейчас активная команда и выполняет её
Разделение команд проходит по id пользователя, изменил в новом патче

2022-05-13 06:51 UTC, lex-cmd commented on TelegramPAI/Application.cs
> +				paiBot.Start(); // получение сообщения если оно есть и запуск бота
Да, так действительно будет проще

2022-05-18 13:05 UTC, appricot-project requested changes

2022-05-18 13:05 UTC, appricot-project commented on TelegramPAI/CommandResultDtoFactory.cs
> +	abstract class CommandResultDtoFactory // класс для создания результата
Какой смысл в этой фабрике? Результаты всё равно зависят от конкретной команды, там и создавать через обычный конструктор.

2022-05-18 13:05 UTC, appricot-project commented on TelegramPAI/Application.cs
> +					paiBot.UserId = telegramApi.GetUserId(); // получение ID пользователя
Зачем в PaiBot иметь идентификатор пользователя? это же атрибут экземпляра команды по логике?

2022-05-18 13:05 UTC, appricot-project commented on TelegramPAI/CommandHandler.cs
> +		private CommandResultDto _result;
Зачем хранить результат команды полем в CommandHandler ? В случае одновременного использования этого же экземпляра CommandHandler это приведёт к ошибкам. Лучше использовать локальные переменные там, где у тебя уже есть результаты команды

2022-05-18 13:05 UTC, appricot-project commented on TelegramPAI/CommandHandler.cs
> +				_commandRepository.Delete(bot.UserId);
а всегда ли нужно удалять команду из репозитория?

2022-05-19 10:20 UTC, lex-cmd commented on TelegramPAI/CommandHandler.cs
> +				_commandRepository.Delete(bot.UserId);
команду нужно удалять когда завершается её выполнение или как?

2022-05-19 10:22 UTC, lex-cmd commented on TelegramPAI/Application.cs
> +					paiBot.UserId = telegramApi.GetUserId(); // получение ID пользователя
получается лучше передавать UserID как параметр в фукцию?

2022-05-19 10:53 UTC, lex-cmd commented on TelegramPAI/CommandResultDtoFactory.cs
> +	abstract class CommandResultDtoFactory // класс для создания результата
Согласен, в данной логике фабрику можно не создавать, но было бы полезно при работе с бд.

2022-06-03 08:05 UTC, merged